name: Pruebas CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd front && npm ci
      - run: cd front && npx quasar test --unit jest